name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Download SUT
        run: |
          curl -L -o app-mbank.jar https://github.com/netology-code/at-homeworks/raw/master/files/app-mbank.jar

      - name: Run SUT
        run: |
          nohup java -jar ./artifacts/app-mbank.jar &
          sleep 15

      - name: Run tests
        run: ./gradlew test